version: "3.0"
services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine3.15
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env

  bj:
    container_name: bj
    build:
      context: ./blackJack
      dockerfile: dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 8000:8000
volumes:
  postgres_volume:
