"""First migration

Revision ID: d59d6e2369b9
Revises: 
Create Date: 2022-11-19 15:15:52.869279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59d6e2369b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('current_user_vk_id', sa.Integer(), nullable=True),
    sa.Column('deck', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status_game', sa.Enum('active', 'finished', name='statusgameenum'), nullable=True),
    sa.Column('players_list', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('allowed_actions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('modification', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('hand', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('active', 'lost', name='statusplayerenum'), nullable=True),
    sa.Column('game_session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('game_sessions')
    # ### end Alembic commands ###
